package com.titleflow.audit;

public enum AuditAction {
    APPLICATION_CREATED,
    APPLICATION_UPDATED,
    APPLICATION_SUBMITTED,
    REVIEW_STARTED,
    MORE_INFO_REQUESTED,
    APPLICATION_APPROVED,
    APPLICATION_REJECTED,
    DOCUMENT_UPLOADED,
    LIEN_CREATED,
    LIEN_RELEASED
}