import jsPDF from "jspdf";

interface VehicleInfo {
    vin: string;
    year: number;
    make: string;
    model: string;
    bodyType: string | null;
    color: string | null;
    odometer: number | null;
}

interface OwnerInfo {
    firstName: string | null;
    lastName: string | null;
    businessName: string | null;
    addressLine1: string;
    addressLine2: string | null;
    city: string;
    state: string;
    zipCode: string;
    phone: string | null;
    email: string | null;
    ownerType: "INDIVIDUAL" | "BUSINESS";
}

interface ApprovedTitleApplication {
    applicationNumber: string;
    status: string;
    vehicle: VehicleInfo;
    buyerOwner: OwnerInfo;
    sellerOwner: OwnerInfo;
    reviewedAt: string | null;
}

function getOwnerDisplayName(owner: OwnerInfo): string {
    if (owner.ownerType === "BUSINESS") {
        return owner.businessName ?? "N/A";
    }

    return `${owner.firstName ?? ""} ${owner.lastName ?? ""}`.trim() || "N/A";
}

function getOwnerAddress(owner: OwnerInfo): string {
    return [
        owner.addressLine1,
        owner.addressLine2,
        owner.city,
        owner.state,
        owner.zipCode,
    ]
        .filter(Boolean)
        .join(", ");
}

function addLabelValue(
    doc: jsPDF,
    label: string,
    value: string | number | null | undefined,
    x: number,
    y: number
) {
    doc.setFont("helvetica", "bold");
    doc.text(`${label}:`, x, y);

    doc.setFont("helvetica", "normal");
    doc.text(String(value ?? "N/A"), x + 48, y);
}

export function downloadGeneratedTitlePdf(application: ApprovedTitleApplication) {
    const doc = new jsPDF();

    const issueDate = application.reviewedAt
        ? new Date(application.reviewedAt).toLocaleDateString()
        : new Date().toLocaleDateString();

    const issuingState = application.buyerOwner.state || "OH";

    const pageWidth = doc.internal.pageSize.getWidth();
    const footerY = 286;

    doc.setFillColor(8, 43, 85);
    doc.rect(0, 0, pageWidth, 32, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text("TitleFlow Generated Title Certificate", 14, 16);

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("Training Copy", 14, 24);

    doc.setTextColor(11, 37, 69);

    let y = 46;

    drawSectionTitle(doc, "Certificate Information", 14, y);
    y += 10;

    addLabelValue(doc, "Title Number", application.applicationNumber, 14, y);
    y += 8;
    addLabelValue(doc, "Issue Date", issueDate, 14, y);
    y += 8;
    addLabelValue(doc, "Issuing State", issuingState, 14, y);
    y += 8;
    addLabelValue(doc, "Status", application.status, 14, y);

    y += 16;

    drawSectionTitle(doc, "Issuing Bureau", 14, y);
    y += 10;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("TitleFlow Bureau of Motor Vehicles", 14, y);
    y += 7;
    doc.text("Digital Title Services Division", 14, y);
    y += 7;
    doc.text(`100 State Records Plaza, ${issuingState}`, 14, y);

    y += 16;

    drawSectionTitle(doc, "Vehicle Information", 14, y);
    y += 10;

    addLabelValue(doc, "VIN", application.vehicle.vin, 14, y);
    y += 8;
    addLabelValue(
        doc,
        "Vehicle",
        `${application.vehicle.year} ${application.vehicle.make} ${application.vehicle.model}`,
        14,
        y
    );
    y += 8;
    addLabelValue(doc, "Body Style", application.vehicle.bodyType, 14, y);
    y += 8;
    addLabelValue(doc, "Color", application.vehicle.color, 14, y);
    y += 8;
    addLabelValue(doc, "Odometer", application.vehicle.odometer, 14, y);

    y += 18;

    drawOwnerColumns(doc, application, y);

    doc.setDrawColor(226, 232, 240);
    doc.line(14, footerY - 8, pageWidth - 14, footerY - 8);

    doc.setFontSize(8);
    doc.setTextColor(91, 100, 114);
    doc.setFont("helvetica", "normal");
    doc.text(
        "Generated by TitleFlow for demo workflow purposes only.",
        14,
        footerY
    );

    doc.save(`TITLE-${application.applicationNumber}.pdf`);
}

function drawSectionTitle(doc: jsPDF, title: string, x: number, y: number) {
    doc.setTextColor(11, 37, 69);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text(title, x, y);
}

function drawOwnerColumns(
    doc: jsPDF,
    application: ApprovedTitleApplication,
    startY: number
) {
    const leftX = 14;
    const rightX = 112;
    const columnWidth = 84;

    drawOwnerBox(
        doc,
        "New Owner / Buyer",
        application.buyerOwner,
        leftX,
        startY,
        columnWidth
    );

    drawOwnerBox(
        doc,
        "Previous Owner / Seller",
        application.sellerOwner,
        rightX,
        startY,
        columnWidth
    );
}

function drawOwnerBox(
    doc: jsPDF,
    title: string,
    owner: OwnerInfo,
    x: number,
    y: number,
    width: number
) {
    const boxHeight = 74;

    doc.setDrawColor(226, 232, 240);
    doc.setFillColor(248, 251, 255);
    doc.roundedRect(x, y, width, boxHeight, 3, 3, "FD");

    doc.setTextColor(11, 37, 69);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text(title, x + 5, y + 9);

    let rowY = y + 20;

    addSmallLabelValue(doc, "Name", getOwnerDisplayName(owner), x + 5, rowY, width - 10);
    rowY += 9;

    addSmallLabelValue(doc, "Owner Type", owner.ownerType, x + 5, rowY, width - 10);
    rowY += 9;

    addSmallLabelValue(doc, "Address", getOwnerAddress(owner), x + 5, rowY, width - 10);
    rowY += 18;

    addSmallLabelValue(doc, "Phone", owner.phone, x + 5, rowY, width - 10);
    rowY += 9;

    addSmallLabelValue(doc, "Email", owner.email, x + 5, rowY, width - 10);
}

function addSmallLabelValue(
    doc: jsPDF,
    label: string,
    value: string | number | null | undefined,
    x: number,
    y: number,
    maxWidth: number
) {
    const labelWidth = 24;
    const textValue = String(value ?? "N/A");

    doc.setFontSize(8);
    doc.setTextColor(11, 37, 69);
    doc.setFont("helvetica", "bold");
    doc.text(`${label}:`, x, y);

    doc.setFont("helvetica", "normal");

    const wrappedText = doc.splitTextToSize(textValue, maxWidth - labelWidth);
    doc.text(wrappedText, x + labelWidth, y);
}